### ISSUE TITLE
Research how to upload file on monday.com

### ISSUE THREAD

**Issue by ceciliachung** [hmwkhmwk/hmwk#33]

**Comment by ulysseses** [comment]
* Official GraphQL API docs (quite unhelpful) https://monday.com/developers/v2#mutations-section-add-file-to-column
* Community posting about file uploads (also a bit unhelpful) https://community.monday.com/t/you-can-now-access-and-upload-files-using-our-api/5997
* NodeJS code tutorial on how to upload file (a bit difficult) https://gist.github.com/yuhgto/edb5d96e088599c2a6ea44860df9117b

**Comment by ulysseses** [comment]
I can't upload image files, but I can upload txt files absolutely fine.

I'm following up with the monday.com community: https://community.monday.com/t/i-cant-upload-png-file/13509

**Comment by lrt98802** [comment]
fixed by #43
